[paths]
app_path = "usr/app"
app_packages_path = "usr/app_packages"
support_path = "usr"
icon.16 = "usr/share/icons/hicolor/16x16/apps/tutorial.png"
icon.32 = "usr/share/icons/hicolor/32x32/apps/tutorial.png"
icon.64 = "usr/share/icons/hicolor/64x64/apps/tutorial.png"
icon.128 = "usr/share/icons/hicolor/128x128/apps/tutorial.png"
icon.256 = "usr/share/icons/hicolor/256x256/apps/tutorial.png"
icon.512 = "usr/share/icons/hicolor/512x512/apps/tutorial.png"
icon.scalable = "usr/share/icons/hicolor/scalable/apps/tutorial.png"
