[paths]
app_path = "{{ cookiecutter.formal_name }}.AppDir/usr/app"
app_packages_path = "{{ cookiecutter.formal_name }}.AppDir/usr/app_packages"
support_path = "{{ cookiecutter.formal_name }}.AppDir/usr"
icon.16 = "{{ cookiecutter.formal_name }}.AppDir/usr/share/icons/hicolor/16x16/apps/{{ cookiecutter.name }}.png"
icon.32 = "{{ cookiecutter.formal_name }}.AppDir/usr/share/icons/hicolor/32x32/apps/{{ cookiecutter.name }}.png"
icon.64 = "{{ cookiecutter.formal_name }}.AppDir/usr/share/icons/hicolor/64x64/apps/{{ cookiecutter.name }}.png"
icon.128 = "{{ cookiecutter.formal_name }}.AppDir/usr/share/icons/hicolor/128x128/apps/{{ cookiecutter.name }}.png"
icon.256 = "{{ cookiecutter.formal_name }}.AppDir/usr/share/icons/hicolor/256x256/apps/{{ cookiecutter.name }}.png"
icon.512 = "{{ cookiecutter.formal_name }}.AppDir/usr/share/icons/hicolor/512x512/apps/{{ cookiecutter.name }}.png"
# icon.scalable = "{{ cookiecutter.formal_name }}.AppDir/usr/share/icons/hicolor/scalable/apps/{{ cookiecutter.name }}.png"
