name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:

defaults:
  run:
    shell: bash  # https://github.com/beeware/briefcase/pull/912

jobs:
  pre-commit:
    name: Pre-commit checks
    uses: beeware/.github/.github/workflows/pre-commit-run.yml@main
    with:
      pre-commit-source: "pre-commit"

  verify-apps:
    name: Build apps
    needs: pre-commit
    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      runner-os: ubuntu-latest
      framework: ${{ matrix.framework }}
      target-platform: linux
      target-format: AppImage
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        framework: [ "toga", "pyside2", "pyside6", "ppb" ]
        exclude:
          # PySide 2 and 6 don't currently publish binary wheels
          # that are compatible with Python 3.11 and/or Ubuntu 18.04
          - python-version: "3.11"
            framework: "pyside2"
          - python-version: "3.11"
            framework: "pyside6"
